import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FlightService } from '../../core/services/flight.service';
import { Flight, FlightSchedule, FlightScheduleTemplate } from '../../core/models/models';

@Component({
  selector: 'app-schedule-management', standalone: true, imports: [CommonModule, ReactiveFormsModule, RouterLink], styles: [`.field-error { color: #dc3545; font-size: 12px; }`],
  template: `
  <div class="container" *ngIf="flight">
    <div class="flex-between"><div><h2>Schedule management</h2><p class="text-muted">{{flight.flightNumber}} · {{flight.origin}} → {{flight.destination}}</p></div><a class="btn btn-primary" [routerLink]="['/flights', flight.flightId, 'schedules', 'new']">+ Special schedule</a></div>
    <div class="card"><h3>Weekly recurring schedule</h3><form [formGroup]="templateForm" (ngSubmit)="saveTemplate()"><div class="form-row"><div class="form-group"><label>Operating days</label><div class="flex"><label *ngFor="let day of days"><input type="checkbox" [checked]="selectedDays.includes(day)" (change)="toggleDay(day, $any($event.target).checked)"> {{day.slice(0,3)}}</label></div></div><div class="form-group"><label>Effective from</label><input type="date" formControlName="effectiveFrom" [min]="today"></div><div class="form-group"><label>Effective to (optional)</label><input type="date" formControlName="effectiveTo" [min]="today"></div></div><div class="form-row"><div class="form-group"><label>Departure</label><input type="time" formControlName="departureTime"></div><div class="form-group"><label>Arrival</label><input type="time" formControlName="arrivalTime"></div><button class="btn btn-primary" [disabled]="templateForm.invalid || selectedDays.length===0">Create recurring schedule</button></div><small class="field-error" *ngIf="templateForm.errors?.['invalidOrder'] && templateForm.touched">Departure time must be before arrival time.</small><small class="field-error" *ngIf="templateForm.errors?.['maximumDuration'] && templateForm.touched">Flight duration cannot exceed 12 hours.</small></form><div class="alert alert-error" *ngIf="error">{{error}}</div></div>
    <div class="card"><h3>Recurring templates</h3><p *ngIf="templates.length===0" class="text-muted">No recurring schedules.</p><table *ngIf="templates.length"><tr><th>Days</th><th>Time</th><th>Effective period</th><th>Status</th><th></th></tr><tr *ngFor="let t of templates"><td>{{t.operatingDays.join(', ')}}</td><td>{{t.departureTime}} – {{t.arrivalTime}}</td><td>{{t.effectiveFrom}} {{t.effectiveTo ? '– '+t.effectiveTo : ''}}</td><td>{{t.active ? 'Active' : 'Inactive'}}</td><td><button *ngIf="t.active" class="btn btn-danger" (click)="deactivate(t)">Deactivate</button></td></tr></table></div>
    <div class="card"><h3>Scheduled occurrences</h3><p *ngIf="schedules.length===0" class="text-muted">No schedules yet.</p><table *ngIf="schedules.length"><tr><th>Date</th><th>Departure</th><th>Arrival</th><th>Status</th><th>Available seats</th></tr><tr *ngFor="let s of schedules"><td>{{s.travelDate}}</td><td>{{s.departureTime}}</td><td>{{s.arrivalTime}}</td><td>{{s.status}}</td><td>{{flight.seatCapacityBusinessClass-s.bookedBusinessSeats}} / {{flight.seatCapacityEconomyClass-s.bookedEconomySeats}} / {{flight.seatCapacityExecutiveClass-s.bookedExecutiveSeats}}</td></tr></table></div>
  </div>`
})
export class ScheduleManagementComponent implements OnInit {
  flight: Flight | null = null; schedules: FlightSchedule[] = []; templates: FlightScheduleTemplate[] = []; error = '';
  readonly days = ['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY']; selectedDays: string[] = []; today = new Date().toISOString().slice(0,10);
  templateForm = new FormBuilder().group({ departureTime: ['', Validators.required], arrivalTime: ['', Validators.required], effectiveFrom: [this.today, Validators.required], effectiveTo: [''] }, { validators: control => { const departure = control.get('departureTime')?.value as string; const arrival = control.get('arrivalTime')?.value as string; if (!departure || !arrival) return null; if (departure >= arrival) return { invalidOrder: true }; const [dh, dm] = departure.split(':').map(Number); const [ah, am] = arrival.split(':').map(Number); return (ah * 60 + am) - (dh * 60 + dm) > 720 ? { maximumDuration: true } : null; } });
  constructor(private api: FlightService, private route: ActivatedRoute) {}
  ngOnInit(): void { const id = Number(this.route.snapshot.paramMap.get('id')); this.api.getById(id).subscribe(f => { this.flight=f; this.load(); }); }
  load(): void { if (!this.flight) return; this.api.getSchedules(this.flight.flightId).subscribe(x=>this.schedules=x); this.api.getScheduleTemplates(this.flight.flightId).subscribe(x=>this.templates=x); }
  toggleDay(day: string, checked: boolean): void { this.selectedDays = checked ? [...this.selectedDays, day] : this.selectedDays.filter(x=>x!==day); }
  saveTemplate(): void { if (!this.flight || this.templateForm.invalid || !this.selectedDays.length) { this.error = this.templateForm.errors?.['maximumDuration'] ? 'Flight duration cannot exceed 12 hours.' : this.templateForm.errors?.['invalidOrder'] ? 'Departure time must be before arrival time.' : ''; return; } const v=this.templateForm.getRawValue(); this.error=''; this.api.createScheduleTemplate(this.flight.flightId,{departureTime:v.departureTime!,arrivalTime:v.arrivalTime!,operatingDays:this.selectedDays,effectiveFrom:v.effectiveFrom!,effectiveTo:v.effectiveTo || null,active:true}).subscribe({next:()=>{this.selectedDays=[];this.templateForm.reset({effectiveFrom:this.today,effectiveTo:'',departureTime:'',arrivalTime:''});this.load();},error:e=>this.error=e?.error?.message ?? 'Unable to create recurring schedule.'}); }
  deactivate(t: FlightScheduleTemplate): void { if (!confirm('Deactivate this recurring schedule? Existing booked and historical occurrences are preserved.')) return; this.api.deactivateScheduleTemplate(t.scheduleTemplateId).subscribe({next:()=>this.load(),error:e=>this.error=e?.error?.message ?? 'Unable to deactivate schedule.'}); }
}
