package com.ams.service.impl;
import com.ams.dto.TicketResponse; import com.ams.entity.*; import com.ams.exception.ResourceNotFoundException; import com.ams.repository.*; import com.ams.service.TicketService;
import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.Authentication; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.List;
@Service public class TicketServiceImpl implements TicketService {
 private final TicketRepository tickets; private final UserRepository users; private final BookingRepository bookings; private final PaymentRepository payments; public TicketServiceImpl(TicketRepository tickets, UserRepository users, BookingRepository bookings, PaymentRepository payments){this.tickets=tickets;this.users=users;this.bookings=bookings;this.payments=payments;}
 @Override @Transactional(readOnly=true) public TicketResponse getById(Integer id){return response(authorize(tickets.findById(id).orElseThrow(()->new ResourceNotFoundException("Ticket with ID "+id+" not found"))));}
 @Override @Transactional(readOnly=true) public TicketResponse getByNumber(String n){return response(authorize(tickets.findByTicketNumber(n).orElseThrow(()->new ResourceNotFoundException("Ticket "+n+" not found"))));}
 @Override @Transactional public List<TicketResponse> getByBooking(Integer id){List<Ticket> found=tickets.findByBookingBookingId(id); if(found.isEmpty()) found=List.of(createHistoricalTicket(id)); return found.stream().map(ticket->response(authorize(ticket))).toList();}
 @Override @Transactional(readOnly=true) public List<TicketResponse> getMyTickets(){User u=currentUser();return tickets.findByUserUserId(u.getUserId()).stream().map(this::response).toList();}
 private Ticket authorize(Ticket t){ Authentication a=SecurityContextHolder.getContext().getAuthentication(); boolean staff=a!=null&&a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN")||x.getAuthority().equals("ROLE_SUPER_ADMIN")); if(!staff&&(a==null||!t.getUser().getUserName().equals(a.getName())))throw new AccessDeniedException("You may only view your own tickets"); return t; }
 private User currentUser(){Authentication a=SecurityContextHolder.getContext().getAuthentication();return users.findByUserName(a.getName()).orElseThrow(()->new ResourceNotFoundException("Authenticated user not found"));}
 private Ticket createHistoricalTicket(Integer bookingId){ Booking b=bookings.findById(bookingId).orElseThrow(()->new ResourceNotFoundException("Booking with ID "+bookingId+" not found")); authorizeBooking(b); Payment p=payments.findByBookingBookingId(bookingId).orElseThrow(()->new ResourceNotFoundException("No successful payment found for booking "+bookingId)); if(!"SUCCESS".equals(p.getStatus())||b.getTicketNumber()==null) throw new ResourceNotFoundException("No issued ticket found for booking "+bookingId); FlightSchedule s=b.getFlightSchedule(); Flight f=s.getFlight(); Carrier c=f.getCarrier(); Ticket t=new Ticket();t.setTicketNumber(b.getTicketNumber());t.setBooking(b);t.setUser(b.getUser());t.setPayment(p);t.setFlightId(f.getFlightId());t.setCarrierId(c.getCarrierId());t.setCarrierName(c.getCarrierName());t.setCarrierCode(c.getCarrierCode());t.setFlightNumber(f.getFlightNumber());t.setOrigin(f.getOrigin());t.setDestination(f.getDestination());t.setTravelDate(s.getTravelDate());t.setDepartureTime(s.getDepartureTime());t.setArrivalTime(s.getArrivalTime());t.setSeatCategory(b.getSeatCategory());t.setNumberOfSeats(b.getNoOfSeats());t.setBaseFare(b.getBookingAmount()/b.getNoOfSeats());t.setDiscountAmount(0d);t.setPaidAmount(b.getBookingAmount());t.setTicketStatus("CANCELLED".equals(b.getBookingStatus())?"CANCELLED":"CONFIRMED");t.setIssuedAt(b.getBookingDateTime());return tickets.save(t); }
 private void authorizeBooking(Booking b){ Authentication a=SecurityContextHolder.getContext().getAuthentication(); boolean staff=a!=null&&a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN")||x.getAuthority().equals("ROLE_SUPER_ADMIN")); if(!staff&&(a==null||!b.getUser().getUserName().equals(a.getName())))throw new AccessDeniedException("You may only view your own tickets"); }
 private TicketResponse response(Ticket t){ TicketResponse r=new TicketResponse();r.ticketId=t.getTicketId();r.ticketNumber=t.getTicketNumber();r.bookingId=t.getBooking().getBookingId();r.userId=t.getUser().getUserId();if(t.getPassenger()!=null){r.passengerId=t.getPassenger().getPassengerId();r.passengerName=t.getPassenger().getPassengerName();r.passengerAge=t.getPassenger().getAge();}r.flightId=t.getFlightId();r.carrierId=t.getCarrierId();r.paymentId=t.getPayment().getPaymentId();r.carrierName=t.getCarrierName();r.carrierCode=t.getCarrierCode();r.flightNumber=t.getFlightNumber();r.origin=t.getOrigin();r.destination=t.getDestination();r.travelDate=t.getTravelDate();r.departureTime=t.getDepartureTime();r.arrivalTime=t.getArrivalTime();r.seatCategory=t.getSeatCategory();r.numberOfSeats=t.getNumberOfSeats();r.baseFare=t.getBaseFare();r.discountAmount=t.getDiscountAmount();r.paidAmount=t.getPaidAmount();r.paymentStatus=t.getPayment().getStatus();r.ticketStatus=t.getTicketStatus();r.issuedAt=t.getIssuedAt();r.refundAmount=t.getRefundAmount();r.cancelledAt=t.getCancelledAt();return r; }
}
