import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { FlightService } from '../../core/services/flight.service';
import { FlightSearchResult } from '../../core/models/models';
import { AIRPORTS_DATA } from '../../core/models/airports';

@Component({ selector: 'app-scheduled-flights', standalone: true, imports: [CommonModule, ReactiveFormsModule], template: `<div class="container"><div class="card"><h2>Scheduled Flights</h2><p class="text-muted">Explore flights scheduled for the upcoming days.</p><form [formGroup]="form" (ngSubmit)="search()"><div class="form-row"><div class="form-group"><label>Origin</label><select formControlName="origin"><option value="">Select origin</option><option *ngFor="let a of airports" [value]="a.city">{{a.city}} ({{a.code}})</option></select></div><div class="form-group"><label>Destination</label><select formControlName="destination"><option value="">Select destination</option><option *ngFor="let a of airports" [value]="a.city">{{a.city}} ({{a.code}})</option></select></div></div><button class="btn btn-primary" [disabled]="form.invalid">View Scheduled Flights</button></form></div><div *ngIf="searched"><div class="card" *ngIf="!results.length">No flights scheduled for this route.</div><section *ngFor="let group of groups"><h3>{{group.date}}</h3><div class="card" *ngFor="let f of group.flights"><strong>{{f.carrierName}} · {{f.flightNumber}}</strong><p>{{f.origin}} → {{f.destination}} · {{f.departureTime}} → {{f.arrivalTime}}</p><p>Economy ₹{{f.economyFare}} ({{f.availableEconomySeats}} seats) · Business ₹{{f.businessFare}} · Executive ₹{{f.executiveFare}}</p><button class="btn btn-primary" (click)="select(f)">Select Flight</button></div></section></div></div>` })
export class ScheduledFlightsComponent { airports=AIRPORTS_DATA; results: FlightSearchResult[]=[]; searched=false; private fb=inject(FormBuilder); form=this.fb.group({origin:['',Validators.required],destination:['',Validators.required]}); constructor(private api:FlightService,private router:Router){} get groups(){return Object.entries(this.results.reduce((a:any,f)=>{(a[f.travelDate]??=[]).push(f);return a;},{})).map(([date,flights])=>({date,flights:flights as FlightSearchResult[]}));} search(){if(this.form.invalid)return;const v=this.form.getRawValue();if(v.origin===v.destination)return;this.api.scheduled(v.origin!,v.destination!).subscribe({next:r=>{this.results=r;this.searched=true;},error:()=>{this.results=[];this.searched=true;}})} select(f:FlightSearchResult){this.router.navigate(['/bookings/new'],{state:{flight:f}})} }
